const fs = require('fs');

// 1. Update index.html
let html = fs.readFileSync('index.html', 'utf8');

// Replace Toggle Dark Mode buttons with Theme buttons
html = html.replace(
    '<button id="themeToggle">Toggle Dark Mode</button>',
    '<button id="themeBtnHeader">🎨 Themes</button>'
);
html = html.replace(
    '<button onclick="document.getElementById(\'themeToggle\').click()">Toggle Dark Mode</button>',
    '<button id="themeBtnSidebar">🎨 Themes</button>'
);

// Insert Theme Modal before sidebarOverlay
const themeModalHtml = `
<!-- Theme Modal -->
<div id="themeModal" class="modal hidden">
    <div class="modal-content" style="max-width: 500px;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <h3>Select Theme</h3>
            <button id="closeThemeModalBtn" style="background:transparent; border:none; font-size:1.5rem; padding:0; box-shadow:none;">✕</button>
        </div>
        <div style="margin-bottom: 15px; margin-top: 10px;">
            <button id="modalDarkModeToggle" style="width: 100%; font-weight: bold;">🌙 Toggle Dark Mode</button>
        </div>
        <h4>Light Backgrounds (20 Colors)</h4>
        <div id="colorPalette" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(40px, 1fr)); gap: 10px; margin-top: 10px;">
            <!-- Color circles generated by JS -->
        </div>
    </div>
</div>
`;

html = html.replace('    <div id="sidebarOverlay" class="sidebar-overlay"></div>', themeModalHtml + '\n    <div id="sidebarOverlay" class="sidebar-overlay"></div>');

fs.writeFileSync('index.html', html, 'utf8');

// 2. Update app.js
let js = fs.readFileSync('app.js', 'utf8');

const themeLogic = `
// --- THEME LOGIC ---
const lightThemes = Array.from({length: 20}).map((_, i) => {
    const hue = Math.floor(i * (360 / 20));
    return {
        id: \`light-\${i}\`,
        bg: \`hsl(\${hue}, 80%, 96%)\`,
        btn: \`hsl(\${hue}, 60%, 90%)\`,
        hover: \`hsl(\${hue}, 60%, 85%)\`,
        task: \`hsl(\${hue}, 20%, 99%)\`,
        border: \`hsl(\${hue}, 30%, 85%)\`
    };
});

const themeModal = document.getElementById('themeModal');
const closeThemeModalBtn = document.getElementById('closeThemeModalBtn');
const colorPalette = document.getElementById('colorPalette');
const modalDarkModeToggle = document.getElementById('modalDarkModeToggle');

if (document.getElementById('themeBtnHeader')) {
    document.getElementById('themeBtnHeader').addEventListener('click', () => {
        themeModal.classList.remove('hidden');
        renderColorPalette();
    });
}
if (document.getElementById('themeBtnSidebar')) {
    document.getElementById('themeBtnSidebar').addEventListener('click', () => {
        themeModal.classList.remove('hidden');
        renderColorPalette();
        toggleSidebar(true);
    });
}
if (closeThemeModalBtn) {
    closeThemeModalBtn.addEventListener('click', () => themeModal.classList.add('hidden'));
}

function renderColorPalette() {
    colorPalette.innerHTML = '';
    lightThemes.forEach((t, index) => {
        const btn = document.createElement('div');
        btn.style.width = '40px';
        btn.style.height = '40px';
        btn.style.borderRadius = '50%';
        btn.style.backgroundColor = t.bg;
        btn.style.border = '2px solid ' + t.border;
        btn.style.cursor = 'pointer';
        btn.style.transition = 'transform 0.2s';
        
        if (state.theme === t.id || (state.theme === 'light' && index === 7)) { // 7 is a nice greenish default fallback
            btn.style.boxShadow = '0 0 0 3px var(--text-color)';
        }
        
        btn.addEventListener('mouseover', () => btn.style.transform = 'scale(1.1)');
        btn.addEventListener('mouseout', () => btn.style.transform = 'scale(1)');
        btn.addEventListener('click', () => {
            state.theme = t.id;
            applyTheme();
            syncTheme();
            renderColorPalette();
        });
        colorPalette.appendChild(btn);
    });
}

modalDarkModeToggle.addEventListener('click', () => {
    state.theme = 'dark';
    applyTheme();
    syncTheme();
    renderColorPalette();
    themeModal.classList.add('hidden');
});

function applyTheme() {
    if (state.theme === 'dark') {
        document.documentElement.setAttribute('data-theme', 'dark');
        document.documentElement.style.removeProperty('--bg-color');
        document.documentElement.style.removeProperty('--btn-bg');
        document.documentElement.style.removeProperty('--btn-hover');
        document.documentElement.style.removeProperty('--task-bg');
        document.documentElement.style.removeProperty('--border-color');
    } else {
        document.documentElement.setAttribute('data-theme', 'light');
        
        let selectedTheme = lightThemes.find(t => t.id === state.theme);
        if (!selectedTheme) {
            // Default to something greenish if state.theme is just 'light'
            selectedTheme = lightThemes[7]; 
        }
        
        document.documentElement.style.setProperty('--bg-color', selectedTheme.bg);
        document.documentElement.style.setProperty('--btn-bg', selectedTheme.btn);
        document.documentElement.style.setProperty('--btn-hover', selectedTheme.hover);
        document.documentElement.style.setProperty('--task-bg', selectedTheme.task);
        document.documentElement.style.setProperty('--border-color', selectedTheme.border);
    }
}
// --- END THEME LOGIC ---
`;

// Replace the old toggleTheme and applyTheme
js = js.replace(/function applyTheme\(\) \{[\s\S]*?\}/, "");
js = js.replace(/function toggleTheme\(\) \{[\s\S]*?\}/, "");
js = js.replace("document.getElementById('themeToggle').addEventListener('click', toggleTheme);", "");

js += '\n' + themeLogic;

fs.writeFileSync('app.js', js, 'utf8');

console.log('Successfully updated themes!');
